title: Laura D Vega
url: https://LunaAlphaLyrae.github.io
baseurl: ""
description: Astrophysicist & Postdoctoral Researcher
lang: en

# Site visuals and links
logo: /images/laura_vega_profile.jpeg
resume_url: https://github.com/LunaAlphaLyrae/Laura_Vega_CV/blob/build/Laura_Vega_CV.pdf

# Contact form (Formspree). Set to your form ID to enable.
formspree_id:

# Social/SEO
twitter:
  username: LunaAlphaLyrae
social:
  name: Laura D. Vega
  links:
    - https://github.com/LunaAlphaLyrae

# GitHub Pages-compatible plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Markdown
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Exclusions
exclude:
  - README.txt
  - README.md
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
